version: '3.8'
services:
  movies:
    image: chathurapriyadasun/payhubmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  cartoons:
    image: chathurapriyadasun/payhubcartoons:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  bank:
    image: chathurapriyadasun/payhubbank:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  
  news:
    image: chathurapriyadasun/payhubnews:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3